### PR TITLE
Bootstrap fixes

### PR DESCRIPTION
**Pull request by embray**
A few miscellaneous issues with ah_bootstrap.py in master that came up during release testing.  See the commit messages for details.

### CODE REVIEW

**Comment by astrofrog** [comment]
The AppVeyor failure is unrelated and just due to graphviz not installing properly in one job (but no other failures)

**Comment by astrofrog** [comment]
Travis says 'go', so merging this (as mentioned above, appveyor failure can be ignored). Thanks @embray!

**Comment by embray** [comment]
Why isn't graphviz installing?

**Comment by astrofrog** [comment]
It was a temporary timeout - 2 out of 3 builds worked.

**Pull request merged**
