### PR TITLE
Replaced copy2 with copy in build_ext

### LINKED ISSUE #255: shutil.copy2 in build_ext
I'm running into a very strange issue on a Linux-based compute cluster. When trying to build one of my packages (based off of the package template), running `python setup.py build` dies almost immediately with:

```
running build
running build_py
running build_ext
error: [Errno 13] Permission denied: 'uncluster/_compiler.c'
```

I tracked it down and it looks like it is [this line](https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/commands/build_ext.py#L258) causing the problem. For some reason, `shutil.copy2()` fails on this system even though I have permissions from bash (`cp` and `cp -p` both work fine). Interestingly, if I change this to `shutil.copy()` instead, I don't get an error. 

So, I'm wondering why `shutil.copy2()` is used here instead of `shutil.copy()`?

### PR DESCRIPTION
**Pull request by pllim**
Replaced `copy2()` with `copy()`. Minor PEP8 cleanups on `build_ext.py`. Fixes #255.

### CODE REVIEW

**Comment by bsipocz** [comment]
(wow, the new gh features are look useful this time, I'm still just discovering them)

**Comment by pllim** [comment]
I don't understand the Travis errors:
```
========================= 60 passed in 119.01 seconds ==========================

The command "py.test --cov astropy_helpers --cov-config $(pwd)/astropy_helpers/tests/coveragerc astropy_helpers" exited with 0.
after_success

3.69s$ coveralls

Submitting coverage to coveralls.io...

Coverage submitted!

Job #729.1

https://coveralls.io/jobs/18874553

Done. Your build exited with 0.

/Users/travis/build.sh: line 109: shell_session_update: command not found
```

**Comment by bsipocz** [comment]
@pllim - That is an unrelated issue and @astrofrog fixed it in ``ci-helpers`` now. 

Someone with commit right could restart the travis in this PR please, just to make sure it passes?

**Comment by pllim** [comment]
I can see a "restart job" button (maybe because I am the author of the PR) but nothing happens when I click on it. :slightly_frowning_face:

**Comment by bsipocz** [comment]
Yes, I tried that too with no apparent results (it even says "Build was
successfully restarted", but actually it isn't). I've long suspected that
something is wrong with the way travis handles the rights, e.g I can cancel
builds for some of the repos for which I don't have commit, but can't do
that for even my own PRs in others.

**Comment by astrofrog** [comment]
I just restarted it

**Comment by pllim** [comment]
Thanks! I think it passed now.

**Comment by astrofrog** [comment]
Thanks @pllim!

**Pull request merged**
