### PR TITLE
Hack to pass -coverage to linker

### LINKED ISSUE #432: OpenMP detection broken when building with -coverage
Detection of OpenMP support when building with the `-coverage` option (see #374) is broken again because the `CFLAGS` environment variable is propagated to the compiler invocation but not the linker invocation. The environment variable `CFLAGS=-coverage` normally tells the build process to add the `-coverage` option to both compiler AND linker commands for C binaries, but as shown below it is only passed to the compiler. As a result, the executable fails to run.

```
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -coverage -fPIC -c test_openmp.c -o objects/test_openmp.o -fopenmp
gcc -pthread objects/test_openmp.o -o test_openmp -fopenmp
objects/test_openmp.o: In function `_GLOBAL__sub_I_65535_0_test_openmp.c':
test_openmp.c:(.text.startup+0x38): undefined reference to `__gcov_init'
objects/test_openmp.o:(.data.rel+0x20): undefined reference to `__gcov_merge_add'
collect2: error: ld returned 1 exit status
```

### PR DESCRIPTION
**Pull request by pllim**
My feeble attempt to fix #432 . Better solution is certainly welcome!

p.s. Not sure how to test it as helpers is a submodule not an installed package.

### CODE REVIEW

**Comment by pllim** [comment]
I don't understand how this error could be related:
```
Exception occurred:
  File "/tmp/pytest-of-travis/pytest-0/test_build_docs_cli_l_0/test_pkg/.eggs/sphinx_automodapi-0.9-py3.6.egg/sphinx_automodapi/automodsumm.py", line 136, in run
    self.warnings = []
AttributeError: can't set attribute
```

**Comment by bsipocz** [comment]
The error is unrelated, and it's present on master, too. I don't yet see why it's failing, but suspect we can expect some new failures with the new sphinx version...

**Comment by astrofrog** [comment]
@pllim: if you want to try out the changes, see these new guidelines I just added:

https://github.com/astropy/astropy-helpers#notes-for-astropy-helpers-contributors

**Comment by pllim** [comment]
@astrofrog , is there an alternative to `build_docs`? I am currently stuck with Windows 10 and building doc on Windows has known issues. 😬 🐰 🕳

**Comment by astrofrog** [comment]
@pllim - well any command really, e.g. ``python setup.py build``

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy-helpers/pull/434#issuecomment-452320796

I created a new conda env with Python 3.7. Installed helpers as instructed into it. Then built `astropy` with the option to use system helpers, as instructed. No errors. However, this patch addresses a bug related to C coverage checks, so I am not sure the steps I ran would have caught any bug anyway. 🤷‍♀️

**Comment by pllim** [comment]
BTW, Travis CI failure is unrelated and reported in #436.

**Comment by astrofrog** [comment]
@pllim - can you rebase? Travis should be fixed on master.

**Comment by pllim** [comment]
OK both CI passed now.

**Comment by bsipocz** [comment]
Could you add a changelog here (given that it fixes an existing issue reported).

**Comment by pllim** [comment]
Change log added. 😄

**Comment by bsipocz** [comment]
Thanks!

**Comment by bsipocz** [comment]
Maybe a premature merge, sorry about it, I was only looking at the approved status.

**Pull request merged**
