### PR TITLE
Fixes to version.py

### PR DESCRIPTION
**Pull request by embray**
These are some mostly minor fixes to `version.py` generation.  But it will improve the generation of "static" version.pys that do not contain any git-related functions.  This also ensures that for release versions only the static version.py will be generated.

A later fix will add hooks to the `sdist` command to ensure that:
a) The package is always built before running sdist (see #53)
b) A static `version.py` will always be generated for creating an sdist.

But I want to make that fix for a later version I think.  It's too late to do that for 1.0 unless it really appears critical.  I don't think it will be though, with the setup.py fix (as long as the same fix is added to Astropy as well as to package-template.

Note also this PR branched off on #136.

### CODE REVIEW

**Comment by embray** [comment]
Added to this an additional fix to address #121.

**Comment by embray** [comment]
I need to double-check, but I believe this also fixes #107.

**Comment by embray** [comment]
Confirmed, ce29656 also fixes #107.  I want to see if I can come up with a test for that though.

**Comment by embray** [comment]
Furthermore, this also should fix #114.

**Comment by eteq** [comment]
Also, this should fix astropy/astropy#3475, correct?

**Comment by astrofrog** [comment]
@embray - is this good to go once AppVeyor passes?

**Comment by embray** [comment]
So...close...

**Comment by embray** [comment]
Rebased and added a changelog entry.  Should be no need to re-run the tests.

**Pull request merged**
