### PR TITLE
rename _eva_ to apyhtest_eva

### LINKED ISSUE #222: Figure out why the travis tests are failing on the "eva" version name
About half of the helpers' tests are currently failing due to a few instances of ``SystemExit: error: Invalid distribution name or version syntax: -eva--1.0.dev1``.  E.g., https://travis-ci.org/astropy/astropy-helpers/builds/115207264

It doesn't seem to be affecting the functionality, so maybe it's a change in how version parsing works?  @astrofrog, I think you were going to look at this?  Or maybe @embray has some insight?

### PR DESCRIPTION
**Pull request by eteq**
This is an effort to address the problem in #222 based on @astrofrog's https://github.com/astropy/astropy-helpers/issues/222#issuecomment-210867813 .

I'm actually having some trouble reproducing the issue locally - it *may* be that setuptools 21.x has fixed it?  It's probably good to have this in for insurance anyway, though...  

At any rate, let's see if the tests pass. If so, then I think this closes #222.

### CODE REVIEW

**Comment by embray** [comment]
Weird, but okay.  Anyone have any idea what's wrong with the CI?

**Comment by astrofrog** [comment]
Not sure, it seems to be related to a heading underline being the wrong length, presumably because of the package name changing length?

```
cython_testpackage = local('/tmp/pytest-0/test_am_replacer_cython0/test_pkg')

[1m    def test_am_replacer_cython(cython_testpackage):[0m
[1m        """[0m
[1m        Tests replacing an ".. automodapi::" for a Cython module.[0m
[1m        """[0m
[1m    [0m
[1m        from ..automodapi import automodapi_replace[0m
[1m    [0m
[1m        fakeapp = FakeApp()[0m
[1m        result = automodapi_replace(am_replacer_cython_str.format(options=''),[0m
[1m                                    fakeapp)[0m
[1m    [0m
[1m>       assert result == am_replacer_cython_expected[0m
[1m[31mE       assert '\nThis comes...comes after\n' == '\nThis comes ...comes after\n'[0m
[1m[31mE         Skipping 56 identical leading characters in diff, use -v to show[0m
[1m[31mE         - -----------------[0m
[1m[31mE         + ----------[0m
[1m[31mE           [0m
[1m[31mE           .. automodule:: apyhtest_eva.unit02[0m
[1m[31mE           [0m
[1m[31mE           Functions[0m
[1m[31mE           ^^^^^^^^^[0m
[1m[31mE           [0m
[1m[31mE           .. automodsumm:: apyhtest_eva.unit02[0m
[1m[31mE               :functions-only:[0m
[1m[31mE               :toctree: api/[0m
[1m[31mE           [0m
[1m[31mE           This comes after[0m```

**Comment by eteq** [comment]
Oops, yeah, my bad.  Will fix that and then rebase

**Comment by eteq** [comment]
(and note that this isn't getting a milestone because it's a testing-only change)

**Comment by eteq** [comment]
OK, this is now passing (the appveyor issue seems to be due to graphviz's web site being down...). @embray and/or @astrofrog, look good to you?

**Comment by astrofrog** [comment]
:+1:

**Comment by eteq** [comment]
Alright - merging!

**Comment by bsipocz** [comment]
@astrofrog - I've noticed that v1.0.7 is failing. Could you please backport this one, it takes care some of the failures. (Locally only one remained when I've cherry-picked these commits).

**Comment by bsipocz** [comment]
Ok, so the branch on top of v.1.0.7 with the cherry-picked commits from various PR is this: https://travis-ci.org/bsipocz/astropy-helpers/builds/136710524

**Pull request merged**
