### PR TITLE
Need to run bootstrap.py when installing the developer version of setuptools

### PR DESCRIPTION
**Pull request by astrofrog**
Currently the build (with allowed failure) was broken due to this

### CODE REVIEW

**Comment by astrofrog** [comment]
The build still fails but for legitimate reasons, so I'll merge this once it otherwise passes, and I'll open an issue about compatibility with the latest setuptools.

**Comment by bsipocz** [comment]
@astrofrog - I'm doing the 1.3 release. Do you think it's fine to backport this one there?

**Comment by astrofrog** [comment]
@bsipocz - not important for the 1.3 release since this is just a CI thing, so up to you

**Comment by bsipocz** [comment]
Then I'm backporting it, it'll be good for practising :)

**Comment by bsipocz** [comment]
This was merged to master as well as 1.3 no matter what the release scripts say (was part of a nested backport merge, thus not picked up).

**Pull request merged**
