### PR TITLE
sphinx.ext.automodsumm broken with Sphinx 1.3

### PR DESCRIPTION
**Pull request by embray**
After updating to Sphinx 1.3 the Sphinx build for Astropy and all affiliated packages doesn't work any more!?
```
$ python setup.py build_sphinx
...
Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/application.py", line 188, in __init__
    self._init_builder(buildername)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/application.py", line 250, in _init_builder
    self.emit('builder-inited')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/application.py", line 497, in emit
    results.append(callback(self, *args))
  File "/Users/deil/code/astropy/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 225, in process_automodsumm_generation
    filestosearch = [x + ext for x in env.found_docs
  File "/Users/deil/code/astropy/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 226, in <listcomp>
    if os.path.isfile(env.doc2path(x))]\
TypeError: Can't convert 'list' object to str implicitly
```
cc @eteq @astrofrog

### CODE REVIEW

**Comment by embray** [comment]
I've converted this to a PR with some related fixes attached.  This should get the docs build pretty much working with Sphinx 1.3 (I'm not sure if everything works *perfectly* but it at least runs and doesn't seem to have any warnings).  

Maybe after the tests for this run I'll attach a new build configuration to the .travis.yml to test against Sphinx 1.3.

**Comment by cdeil** [comment]
Thanks @embray  for fixing this so quickly!

If it works with Sphinx 1.3 on your machine or travis-ci it's probably not necessary, but let me know if you want me to try this branch on my machine.

**Comment by embray** [comment]
One issue it still has is that links to API references are still showing up in black instead of blue.  I wonder if that's just something that needs to be tweaked in the stylesheet for the theme.

**Comment by cdeil** [comment]
@embray – Any chance to get this in soon?
(I'm not looking forward to having to teach my package manager to go back to an old Sphinx version, but I do want to build the docs for the affiliated packages I work on.)

**Comment by embray** [comment]
Hm, well Travis-CI lost its damn mind on that last build, so I'll restart it.  It looks like this change might have broken things with Sphinx 1.2.x now though.  I'll have to go back and re-tinker.

**Comment by embray** [comment]
@astrofrog Any idea what this is about:
```
Error: Cowardly refusing to `sudo brew install`

You can use brew with sudo, but only if the brew executable is owned by root.

However, this is both not recommended and completely unsupported so do so at

your own risk.

The command "source continuous-integration/travis/install_graphviz_$TRAVIS_OS_NAME.sh" failed and exited with 1 during .
```

? I think you set this up.  The travis builds are losing their mind over it.

**Comment by embray** [comment]
@cdeil I think this is nearly fixed, but I need to find out why the CI builds are going belly up.

**Comment by embray** [comment]
Rebased to force a rebuild, now that #152 is in; hopefully now the build should pass on all platforms.

**Pull request merged**
