### PR TITLE
Python version dependent local sphinx inv

### PR DESCRIPTION
**Pull request by bsipocz**
This PR adds python version dependent local sphinx inventories, so sphinx builds can pass without warnings with both python2 and python3. This supersedes #214.

Edit: ~~(Changes to setup_helpers.py are pure PEP8 changes, and can be removed if preferred).~~ it was moved to #226

### CODE REVIEW

**Comment by mhvk** [comment]
@bsipocz - long delay, but now had a look: these changes certainly seem fine, and as it would be good to get python3 builds working properly, I'm all in favour.  I'm not really set up well to test them, though...

**Comment by bsipocz** [comment]
@mhvk - I'm not sure about the best way for the test, there isn't much docs here to do it within the helpers. Maybe the simplest is to update the helpers within astropy/astropy#4481 once this is merged and iron out any problems that come up before it goes into a release.

**Comment by bsipocz** [comment]
Also should this have a changelog? If yes, which milestone?

**Comment by mhvk** [comment]
@bsipocz - yes, sounds good to merge and test in astropy. Would this be for https://github.com/astropy/astropy/pull/4556? As said, it looks good to me, but feel sufficiently unsure that I'd rather have @astrofrog or @eteq have a look.

**Comment by eteq** [comment]
@bsipocz - definitely changelog it. Re: milestone I think this (and the corresponding sphinx builds) should go in 1.2 - generally we've considered "doc changes" to be ok for bugfix branches, but I think this is signficant enough that it's better done in a new major release.

**Comment by bsipocz** [comment]
@eteq - OK. I agree that this is more than a docs change, but maybe we want to provide py3 docs build support for the affiliates before 1.2?

**Comment by bsipocz** [comment]
Changelog added.

**Comment by eteq** [comment]
Hmm, this is an interesting question that perhaps @astrofrog or @embray want to weigh on on: do we want to consider doing a helper 1.2 release *before* the core package?  We can always do 1.2.1 (or later) before the core package 1.2 release...

**Comment by bsipocz** [comment]
@eteq - Rebased, but left the changelog in 1.2. I can move it you decide to include this in 1.1.3 :)

**Comment by eteq** [comment]
@bsipocz - as per discussion on gitter, looks like this is suitable for 1.1.3, so you can move it to that part of the changelog and then we'll merge.

**Comment by eteq** [comment]
(I'm pretty sure the one travis failure is a red herring, and the appveyor issue is the continuing "Chocolatey" business that seems to be some network issue?)

**Comment by bsipocz** [comment]
@eteq - Done.

**Comment by eteq** [comment]
Alright, great.  Merging!

**Pull request merged**
