### PR TITLE
Adding collections.Mapping to the local python3 inventory

### PR DESCRIPTION
**Pull request by bsipocz**
As pointed out in #237 this causes a problem with the python3 sphinx builds (while it still can be imported from the old namespace).

This is also needed for astropy/astropy#4556 to pass.

### CODE REVIEW

**Comment by astrofrog** [comment]
@bsipocz - any idea what happened here?

**Comment by bsipocz** [comment]
@astrofrog - This is weird, the isn't any sphinx test on appveyor so this shouldn't affect anything there.

**Comment by bsipocz** [comment]
Ohh, now I got some vague memories back. The appveyor builds are failing for a long time, but in the last helpers spring we didn't have time to fix it and forgot about it since (at least I forgot about it).

**Comment by astrofrog** [comment]
The AppVeyor failure is unrelated, so merging this.

**Pull request merged**
