### PR TITLE
Fixing compatibility with sphinx <1.5

### PR DESCRIPTION
**Pull request by bsipocz**
#292 seems to broke our compatibility with older sphinx versions. We simply need to test against 1.3, 1.4 and 1.5 to make sure or update the current requirement of ``1.3``

See: #325

### CODE REVIEW

**Comment by bsipocz** [comment]
@astrofrog - the bot is malfunctioning, there is a changelog here...

**Comment by astrofrog** [comment]
I will investigate!

**Comment by pllim** [comment]
Maybe replacing existing line doesn't count as "new change log entry" by the bot's rules. 🤔

**Comment by bsipocz** [comment]
@pllim - that shouldn't matter I guess. Also previous reincarnation of the bot worked (https://github.com/astropy/astropy-helpers/pull/323#issuecomment-313047183), so probably one of my PRs messed it up.

**Comment by pllim** [comment]
My bet is on https://github.com/astropy/astropy-bot/blob/master/changebot/changelog.py#L33 because I notice that this change log here has "====" at the top but that line does not contain version info like Astropy's. Just a guess though.

**Comment by pllim** [comment]
Bot is happy now! 😄

**Comment by bsipocz** [comment]
Thanks @pllim!

**Comment by astrofrog** [comment]
I'm working on an updated version of the bot that won't require this kind of hack

**Comment by bsipocz** [comment]
@astrofrog @eteq - What do you think how critical breaking sphinx compatibility is (1.4 is not that old, the latest of that series was release at the end of last year)? Should we aim to have a helpers 2.0.1 along with astropy 2.0.1?

**Comment by astrofrog** [comment]
I think it makes sense to keep compatibility with at least 1.4+

**Comment by eteq** [comment]
I also agree compatibility with something that recent is fairly important, so it's worth a release.

**Pull request merged**
