### PR TITLE
log.warn is deprecated, so use log.warning instead

### PR DESCRIPTION
**Pull request by keflavich**
At least, that's how I understand this message:

    DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead

### CODE REVIEW

**Comment by bsipocz** [comment]
:+1:

**Comment by eteq** [comment]
@keflavich - hmm, the test failures suggest that some of these's aren't regular python Loggers, and hence don't have `warning`?  Not sure which, though...

**Comment by bsipocz** [comment]
@eteq - You're right, it's a different log ``from distutils import log``. 
I had some deja vu when saw this PR, as remembering that I tried to get rid of similar deprecations, and wondered how this could have slipped through :)

**Comment by eteq** [comment]
So are they *all* the `distutils` log, in which case we should close this, or are some of these regular log objects that should be `warning`?

**Comment by keflavich** [comment]
ah, my bad, I didn't check where `log` was coming from; I was doing global search-and-replaces in other projects where this was all `logging.warn`, which is deprecated.  I'll check tomorrow & maybe just close.

**Comment by eteq** [comment]
OK, great, thanks @keflavich

**Comment by keflavich** [comment]
Can confirm, all `log`s are from distutils:
```
$ ack 'import log'
ah_bootstrap.py
131:from distutils import log

astropy_helpers/commands/build_ext.py
10:from distutils import log, ccompiler, sysconfig

astropy_helpers/commands/build_sphinx.py
12:from distutils import log

astropy_helpers/setup_helpers.py
19:from distutils import log

astropy_helpers/tests/__init__.py
84:    from distutils import log

astropy_helpers/version_helpers.py
29:from distutils import log

ez_setup.py
25:from distutils import log
```

**Pull request closed without merging**
