### PR TITLE
Make `check_submodule` public.

### PR DESCRIPTION
**Pull request by mdboom**
Over in pyasdf, I found it useful to use the `check_submodule` function in `ah-bootstrap` to update the `asdf-standard` submodule.  (See spacetelescope/pyasdf#86).  Over there, I'm using an old version of ah_bootstrap.py, where it was pretty easy to do.  Now I see that it's become a member function and is harder to use independently.  This restores it as a free function and makes it public.  A follow-on (if this makes sense) will be to update the package template to describe how to use this to automatically update git submodules.

### CODE REVIEW

**Comment by embray** [comment]
:-1: in favor of a more general approach to auto-initializing additional submodules as discussed in #74

**Comment by embray** [comment]
I should correct somewhat since there's nothing "non-general" about this.  I guess I'll mostly reiterate my preference for ah_bootstrap to not offer any kind of API of its own.  A function like this could also just as easily go into astropy_helpers.setup_helpers too.  ah_bootstrap is needed to bootstrap astropy-helpers, but it shouldn't be involved in bootstrapping other parts of the package...

**Comment by mdboom** [comment]
Ok.  Just so I'm clear: would you be in favor of a PR that adds this to `astropy_helpers.setup_helpers`, then?

**Comment by embray** [comment]
Sure...

**Comment by mdboom** [comment]
Closed in favor of #155.

**Pull request closed without merging**
