### PR TITLE
Fix for issue #179

### PR DESCRIPTION
**Pull request by RiceMunk**
This should fix issue #179 in the way I described in the OP.

### CODE REVIEW

**Comment by embray** [comment]
Probably fine, but I want to see if I can figure out why that line was there in the first place.

**Comment by embray** [comment]
Okay, looks like that's been there all along (and is also overriding the `white-space: pre` just before it anyways).  I'm going to try building the Astropy docs to see if this change makes anything obviously go awry, and if not we can use it (just add a changelog entry for v1.0.4).

**Comment by RiceMunk** [comment]
Yeah, I was wondering if there were supposed to be two `white-space` entries there, but don't really know enough about CSS to know if that intentional.

Added the changelog entry now to the file I think it's supposed to be in.

**Comment by embray** [comment]
Looks good--I did a test build of the docs and although it's impossible to check every page I don't see this having a whole lot of impact anywhere, so we'll go with it for now.

**Pull request merged**
