### PR TITLE
Limiting versions of setuptools and sphinx

### PR DESCRIPTION
**Pull request by bsipocz**
This is to deal temporarily with the latest travis failures that are not affecting functionality.

See details in #222 and #224.

ping @eteq

### CODE REVIEW

**Comment by bsipocz** [comment]
I think the failure is due to an unrelated coveralls glitch, restarting that build should make it pass.

**Comment by eteq** [comment]
@bsipocz - yep, I think you're right - re-started travis and if it passes this is good to merge.

The Appveyor failures are more mysterious.... but it looks like it's been present for a while so I won't worry about that right now.

**Comment by eteq** [comment]
I really don't get why coveralls is unhappy.  I'm 99% sure its unrelated though, so I'm going to merge this now and we'll see if its consistent over the next few builds.

**Comment by bsipocz** [comment]
> The Appveyor failures are more mysterious.... but it looks like it's been present for a while so I won't worry about that right now.

Seems somewhat related, at least it went wrong at the same time.

**Comment by bsipocz** [comment]
Yep, same problem there, setuptools got upgraded to 20.x.

**Pull request merged**
