### PR TITLE
Remove code from astropy_helpers.utils that isn't used

### PR DESCRIPTION
**Pull request by astrofrog**
These utilities aren't used anymore - and if we do need to deprecate things, the code base for astropy-helpers is now small enough that raising the deprecation warning manually would be more efficient.

### CODE REVIEW

**Comment by astrofrog** [comment]
Huh I wonder why the astropy bot didn't do anything here

**Comment by astrofrog** [comment]
About backporting to LTS: true but I think we shouldn't since this is formally an API change/removal.

**Comment by bsipocz** [comment]
> we shouldn't since this is formally an API change/removal.

we didn't really apply this rule for the helpers.

**Comment by bsipocz** [comment]
Thanks @astrofrog!

**Comment by pllim** [comment]
From the comment, it sounded like the original plan was to move these from `astropy` core to `astropy-helpers`? I can see why as these are generic non-astro functions. But I also have no seen any user request to do so. No (belated) objection here.

**Comment by astrofrog** [comment]
Note that astropy-helpers is only available at setup time, so we couldn't ever actually remove these from astropy core.

**Comment by pllim** [comment]
Maybe back in 2015, this wasn't a submodule yet? Ah, well. :woman_shrugging:

**Pull request merged**
