### PR TITLE
Adding builtins.object to local python3 inventory to fix broken links ...

### PR DESCRIPTION
**Pull request by bsipocz**
...when build_sphinx was run with python3

For some unknown reason, the ``object`` class is referenced as ``builtins.object`` rather than just ``object`` when ``build_sphinx`` is run with python3. And also for some unknown reason this is missing from the official python3 ``objects.inv``. Updating our local inventory solves the broken link problem.

Came up in photutils (https://github.com/astropy/photutils/pull/236), but it's also a problem in the astropy core.

### CODE REVIEW

**Comment by bsipocz** [comment]
I've just added a few more links. Now astropy core docs builds with python3 without warnings.

**Comment by cdeil** [comment]
@bsipocz - Thanks! Is this maybe something that should be reported to the Python or Sphinx devs?

All travis-ci builds fail, but I think this is an unrelated issue?
https://travis-ci.org/astropy/astropy-helpers/jobs/47388529

**Comment by astrofrog** [comment]
The Travis failure is probably due to an upgrade in certain packages in conda. The previous build that worked was:

```
    cython-0.21.1              |           py27_0         5.0 MB
    docutils-0.12              |           py27_0         636 KB
    py-1.4.20                  |           py27_0         120 KB
    markupsafe-0.23            |           py27_0          30 KB
    pygments-1.6               |           py27_0         864 KB
    setuptools-7.0             |           py27_0         436 KB
    numpy-1.9.1                |           py27_0         7.7 MB
    pip-1.5.6                  |           py27_0         1.3 MB
    pytest-2.5.2               |           py27_0         173 KB
    jinja2-2.7.3               |           py27_1         308 KB
    sphinx-1.2.3               |           py27_0        1005 KB
```

The version here is:

```
    cython-0.21.2              |           py27_0         5.0 MB
    docutils-0.12              |           py27_0         636 KB
    py-1.4.20                  |           py27_0         120 KB
    markupsafe-0.23            |           py27_0          30 KB
    pygments-1.6               |           py27_0         864 KB
    setuptools-11.3.1          |           py27_0         430 KB
    numpy-1.9.1                |           py27_0         7.7 MB
    pip-6.0.6                  |           py27_0         1.5 MB
    pytest-2.5.2               |           py27_0         173 KB
    jinja2-2.7.3               |           py27_1         308 KB
    sphinx-1.2.3               |           py27_0        1005 KB
```

The packages that have been updated are cython, setuptools, pip and pytest.

**Comment by astrofrog** [comment]
This error can be reproduced locally and appears to be due to the setuptools upgrade from 7.0 to 11.3.1. I'll open a new issue.

**Comment by bsipocz** [comment]
In the meantime I've found it to be reported already on the sphinx side, but haven't found anything on the python issue tracker...

https://github.com/sphinx-doc/sphinx/issues/1582

**Comment by astrofrog** [comment]
@bsipocz - can you rebase? @embray fixed the tests :)

**Comment by bsipocz** [comment]
@astrofrog - rebased

**Comment by embray** [comment]
Thanks!

**Pull request merged**
