### PR TITLE
Updating bundled numpydoc version to v0.6

### PR DESCRIPTION
**Pull request by bsipocz**
@astrofrog @eteq - Do we need to backport these kinf of updates? What about changelog, I assume that could be useful?

### CODE REVIEW

**Comment by pllim** [comment]
I thought Sphinx uses `napoleon` extension now instead of `numpydoc`?

**Comment by bsipocz** [comment]
Afaik we haven't switched yet (e.g. https://github.com/astropy/astropy/issues/3974), and nevertheless I'm not sure we can that easily remove numpydoc from the helpers without deprecating it first.

**Comment by bsipocz** [comment]
Merging this now, but I'm opening and issue here, too to remind us to switch to ``napoleon`` at some point.

**Comment by bsipocz** [comment]
I think this doesn't need a changelog entry, but please confirm @astrofrog.

**Pull request merged**
