### PR TITLE
Remove PY2 compat for C compiler

### PR DESCRIPTION
**Pull request by pllim**
We don't need to check whether it is PY2 or PY3 anymore, right?

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @pllim, indeed.

**Comment by bsipocz** [comment]
A wonder why the codecov bot behaves here, but double comment on the astropy repo.

Anyway, this is all green now, so I'm merging. Thanks again @pllim!

**Comment by pllim** [comment]
Maybe because I changed the C stuff, it doesn't know how to calculate? 🤷‍♀

**Comment by bsipocz** [comment]
I don't mean the content of the comment, just that fact that finally it doesn;'t comment twice. Not sure why it does it for astropy core, and I also heard it really badly behaves for other repos, e.g. e.g the bot is muted for numpy due to the repeated commenting.

**Comment by pllim** [comment]
There was a similar behavior from `astropy-bot` before. I think @astrofrog said it was race condition when posting comment from multiple events that happen too closely in time. That was why we moved away from bot posting a comment, and now it posts status.

**Pull request merged**
