### PR TITLE
Fix errors reported by pyflakes

### PR DESCRIPTION
**Pull request by astrofrog**
Fixes https://github.com/astropy/astropy-helpers/issues/305 - I also found another error that I fixed here, and fixed some other more minor issues.

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @astrofrog. It all looks good to me.

Do you think it should go into 1.3.2, or 2.0? My best guess is that the current 1.3.x branch has issues with setuptools when a too new version is picked up from conda-forge (at least I see the jinja2 issues only on travis for both gammapy/photutils/sunpy, some are linked in #302), but not locally where I have an ancient version. I'm now testing this hypothesis on travis.

**Comment by astrofrog** [comment]
I would say 1.3.2 since it fixes actual potential bugs

**Comment by bsipocz** [comment]
Since this is mostly for affiliates that doesn't want to upgrade to v2.0 straight away, I've released astropy core 1.3.3 without the docs there needs some other fixes, too to be sphinx 1.6 compatible.

The 1.3.x branch here is currently failing with gammapy/photutils but passed with astropy. So anything can still be backported.

**Comment by bsipocz** [comment]
Why wasn't astropy-bot complaining about the missing milestone and changelog?

**Pull request merged**
