### PR TITLE
Fix leaked temporary directory in check_openmp_support

### PR DESCRIPTION
**Pull request by lpsinger**

### CODE REVIEW

**Comment by pllim** [comment]
Thanks! However, I don't think `astropy-helpers` is actively developed anymore with APE 17 in place (feel free to correct me if I am wrong).

So, you might want to look at https://github.com/astropy/extension-helpers/blob/master/extension_helpers/_openmp_helpers.py instead.

**Comment by lpsinger** [comment]
I'll happily submit a patch for extension-helpers as well. Meanwhile, I haven't converted my own projects to APE 17 yet, so it would be nice to have this fixed for astropy-helpers.

If astropy-helpers has actually been abandoned, then it should say that prominently in the README.

**Comment by pllim** [comment]
Maybe not abandoned per se, but no future development is planned for it. Certainly, a critical bug fix will be acceptable. So, thanks for the PR!

**Comment by astrofrog** [comment]
This looks good to me in principle, and indeed the fix should also be made in extension-helpers. However there are some CI failures that need to be resolved first, I think unrelated to this PR.

**Comment by pllim** [comment]
CI should be fixed once #512 is merged but this will need a rebase. FYI. (I don't have the power to merge it.)

**Comment by pllim** [comment]
Closing due to archiving the repo. Thanks anyway!

**Pull request closed without merging**
