### PR TITLE
Clean up openmp test file

### LINKED ISSUE #461: openmp_enabled.py should be a temp file rather than in the repo
Running tests dumps a `openmp_enabled.py` file in the main repo directory. It should rather go into a temporary file that gets deleted after the tests are run.

Content:
```
# Autogenerated by 's setup.py on 2019-04-23 00:18:30

def is_openmp_enabled():
    """
    Determine whether this package was built with OpenMP support.
    """
    return False`
```

### PR DESCRIPTION
**Pull request by pllim**
Fix #461

### CODE REVIEW

**Comment by pllim** [comment]
Alternate way if to retain the test as a function (instead of turning it into a class) but put the whole thing under `try-finally` block, but I prefer this way personally.

**Comment by bsipocz** [comment]
Failure should be related, I see it locally, too.

**Comment by pllim** [comment]
Weird, it passed when I ran with `pytest testfilename`...

**Comment by pllim** [comment]
Oh... It is failing in another test file... Hmm.

**Pull request closed without merging**
