### PR TITLE
Fix encoding error with automodapi_writereprocessed and py2

### PR DESCRIPTION
**Pull request by saimn**
`automodapi_writereprocessed` was not working on Python 2

### CODE REVIEW

**Comment by pllim** [comment]
Is this to fix #243?

**Comment by saimn** [comment]
@pllim - No, it unrelated.

**Comment by saimn** [comment]
Up ! (it is really a minor fix, useful mainly for debugging purpose.)

**Comment by bsipocz** [comment]
This looks good to me, and already got the thumbs up from @embray, so I'm merging. Tagged as no changelog-needed, but I'm half sure about that, maybe one would be useful.

**Comment by saimn** [comment]
Thanks @bsipocz ! No changelog is fine for me.

**Pull request merged**
