### PR TITLE
MNT: Fix Giles URL

### PR DESCRIPTION
**Pull request by pllim**
cc @Cadair

### CODE REVIEW

**Comment by bsipocz** [comment]
Ouch, master is badly  broken, but I go ahead and merge this as it's unrelated to that.

Also, Giles doesn't seem to pick this up, but again the url update is the right thing (and since giles doesn't pick up build anywhere since the recent past, the issue is something more fundamental upstream).

**Comment by bsipocz** [comment]
thanks @pllim!

**Comment by pllim** [comment]
` AttributeError: 'CoverageData' object has no attribute 'read_file'` -- Maybe you gotta pin `coverage` like I remember @astrofrog doing in another repo but I don't remember which one now.

**Comment by bsipocz** [comment]
hmm, interesting, it's pinned in ci-helpers...

**Comment by bsipocz** [comment]
OK, that wasn't painful at the end: https://github.com/astropy/ci-helpers/pull/436

**Comment by bsipocz** [comment]
Well, that was a premature statement above. Maybe astropy/ci-helpers#437 is the real one now.

**Pull request merged**
