### PR TITLE
Fixed malformatting of an error message

### PR DESCRIPTION
**Pull request by embray**

### CODE REVIEW

**Comment by embray** [comment]
Should maybe add a test for this code.

**Comment by embray** [comment]
Since I forgot what this was about until now, for reference what this is fixing is that right due to the bug that this fixes, right now if you try to build Astropy from a source checkout and don't have Numpy installed you'll get a mysterious error message:
```
running build_ext
running pre_hook from astropy.modeling.setup_package for build_ext command
running pre_hook from astropy._erfa.setup_package for build_ext command
Traceback (most recent call last):
  File "./setup.py", line 123, in <module>
    **package_info
  File "/internal/1/root/usr/local/lib/python3.4/distutils/core.py", line 149, in setup
    dist.run_commands()
  File "/internal/1/root/usr/local/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/internal/1/root/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/internal/1/root/src/astropy/astropy/astropy_helpers/astropy_helpers/test_helpers.py", line 144, in run
    self._build_temp_install()
  File "/internal/1/root/src/astropy/astropy/astropy_helpers/astropy_helpers/test_helpers.py", line 192, in _build_temp_install
    self.run_command('build')
  File "/internal/1/root/usr/local/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/internal/1/root/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/internal/1/root/usr/local/lib/python3.4/distutils/command/build.py", line 126, in run
    self.run_command(cmd_name)
  File "/internal/1/root/usr/local/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/internal/1/root/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/internal/1/root/src/astropy/astropy/astropy_helpers/astropy_helpers/setup_helpers.py", line 390, in run
    orig_run(self)
  File "/internal/1/root/src/astropy/astropy/astropy_helpers/astropy_helpers/commands/build_ext.py", line 146, in run
    cfn, pyxfn, extension.name))
IndexError: tuple index out of range
```
rather than the useful one stating that Cython must be installed.

**Comment by embray** [comment]
Oops--fixed messed up rebase.

**Comment by cdeil** [comment]
@embray – I think this issue @JonathanDHarris reported might be the one you fixed here?
https://groups.google.com/forum/#!topic/gammapy/00uk0GS4YXc

Looks like it's still failing on Appveyor though:
https://ci.appveyor.com/project/Astropy/astropy-helpers/build/1.0.184/job/b5gvvq8yhjp7aiqn#L288

**Comment by embray** [comment]
Indeed, this can happen when Cython isn't installed.  The bug is just in formatting the error message, so instead of a useful error message the user gets an unrelated traceback.

**Pull request merged**
