### PR TITLE
Updating numpydoc to v0.8.0

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by pllim** [comment]
Huh... Any reason we still need `numpydoc` as opposed to [sphinx.ext.napoleon](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html)?

**Comment by bsipocz** [comment]
Another conversation to have at the coordination meeting? (I vaguely remember it's an unresolved conversation).

**Comment by bsipocz** [comment]
Oh, there you go, it started in 2015 if you follow the refs: https://github.com/astropy/sphinx-astropy/issues/5

**Comment by eteq** [comment]
(see my comment back in the threads @bsipocz issued about how I tried Napolean and couldn't get it to work without spending a lot of time fixing things.  Still might be worth it, but it turns out it's not, at least, a simple drop-in)

**Pull request merged**
